#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR/..

echo ">> Compile the backend"
rm -rf www-server/{backend,isomorphic}/*
node_modules/.bin/tsc --project backend/

echo ">> Compile the SCSS"
node_modules/.bin/node-sass --recursive --output-style expanded --sourceMapEmbed=true frontend/ -o www-server/www

echo ">> Compile the frontend"
node_modules/.bin/webpack --config frontend/webpack.config.js
