#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR/..

echo ">> Compile the backend"
rm -rf www-server/{backend,isomorphic}/* || exit 1
node_modules/.bin/tsc --project backend/ || exit 1

echo ">> Compile the SCSS"
node_modules/.bin/node-sass --recursive --source-map-embed --output-style expanded frontend/ -o www-server/www || exit 1

echo ">> Compile the frontend"
node_modules/.bin/webpack --config frontend/webpack.config.js || exit 1
